// <auto-generated />
using System;
using System.Text.Json;
using CallCenter.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CallCenter.Server.Data.Migrations
{
    [DbContext(typeof(CallCenterDbContext))]
    [Migration("20260924065028_AddCallNotes")]
    partial class AddCallNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CallCenter.Server.Data.Entities.AgentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AppVersion")
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<string>("LaptopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("laptop_id");

                    b.Property<DateTimeOffset>("LoggedInAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_in_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("LoggedOutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_out_at");

                    b.Property<string>("LogoutReason")
                        .HasColumnType("text")
                        .HasColumnName("logout_reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_agent_sessions");

                    b.HasIndex("UserId", "LoggedInAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_sessions_user");

                    b.ToTable("agent_sessions", (string)null);
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<JsonDocument>("After")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<DateTimeOffset>("At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("Before")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity");

                    b.Property<string>("EntityId")
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_log_user_id");

                    b.HasIndex("Entity", "EntityId")
                        .HasDatabaseName("ix_audit_entity");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_branches_name");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_channels");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_channels_name");

                    b.ToTable("channels", (string)null);
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.Classification", b =>
                {
                    b.Property<Guid>("CommunicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("communication_id");

                    b.Property<DateTimeOffset>("ClassifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("classified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ClassifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("classified_by");

                    b.Property<JsonDocument>("CustomValues")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_values")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<bool>("FollowUp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("follow_up");

                    b.Property<int>("FormVersion")
                        .HasColumnType("integer")
                        .HasColumnName("form_version");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("OrderValue")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("order_value");

                    b.Property<bool?>("Resolved")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("CommunicationId")
                        .HasName("pk_classifications");

                    b.HasIndex("ClassifiedBy")
                        .HasDatabaseName("ix_classifications_classified_by");

                    b.HasIndex("CustomValues")
                        .HasDatabaseName("ix_class_custom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CustomValues"), "gin");

                    b.HasIndex("FormVersion")
                        .HasDatabaseName("ix_classifications_form_version");

                    b.HasIndex("ResolvedBy")
                        .HasDatabaseName("ix_classifications_resolved_by");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_class_type");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_classifications_updated_by");

                    b.ToTable("classifications", (string)null);
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.ClassificationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<JsonDocument>("After")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<JsonDocument>("Before")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<Guid>("CommunicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("communication_id");

                    b.HasKey("Id")
                        .HasName("pk_classification_history");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("ix_classification_history_changed_by");

                    b.HasIndex("CommunicationId")
                        .HasDatabaseName("ix_class_hist_comm");

                    b.ToTable("classification_history", (string)null);
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.ClassificationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Colour")
                        .HasColumnType("text")
                        .HasColumnName("colour");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("LabelAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_ar");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_en");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_classification_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_classification_types_name");

                    b.ToTable("classification_types", (string)null);
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.Communication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("integer")
                        .HasColumnName("duration_sec");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("Extension")
                        .HasColumnType("text")
                        .HasColumnName("extension");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LaptopId")
                        .HasColumnType("text")
                        .HasColumnName("laptop_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("PbxUniqueId")
                        .HasColumnType("text")
                        .HasColumnName("pbx_unique_id");

                    b.Property<string>("QueueName")
                        .HasColumnType("text")
                        .HasColumnName("queue_name");

                    b.Property<string>("RemoteName")
                        .HasColumnType("text")
                        .HasColumnName("remote_name");

                    b.Property<string>("RemoteNormalised")
                        .HasColumnType("text")
                        .HasColumnName("remote_normalised");

                    b.Property<string>("RemoteNumberRaw")
                        .HasColumnType("text")
                        .HasColumnName("remote_number_raw");

                    b.Property<string>("SipCallId")
                        .HasColumnType("text")
                        .HasColumnName("sip_call_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("WaitSec")
                        .HasColumnType("integer")
                        .HasColumnName("wait_sec");

                    b.HasKey("Id")
                        .HasName("pk_communications");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_communications_branch_id");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_communications_channel_id");

                    b.HasIndex("PbxUniqueId")
                        .IsUnique()
                        .HasDatabaseName("ux_comm_pbx_unique")
                        .HasFilter("pbx_unique_id IS NOT NULL");

                    b.HasIndex("RemoteNormalised")
                        .HasDatabaseName("ix_comm_remote");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_comm_started");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_comm_status");

                    b.HasIndex("AgentId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_comm_agent_started");

                    b.HasIndex("ContactId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_comm_contact");

                    b.HasIndex("SipCallId", "Extension")
                        .IsUnique()
                        .HasDatabaseName("ux_comm_sip_call")
                        .HasFilter("sip_call_id IS NOT NULL");

                    b.ToTable("communications", null, t =>
                        {
                            t.HasCheckConstraint("ck_communications_direction", "direction IN ('In','Out','None')");

                            t.HasCheckConstraint("ck_communications_kind", "kind IN ('Call','App')");

                            t.HasCheckConstraint("ck_communications_source", "source IN ('AgentApp','AMI','CDR','Manual')");

                            t.HasCheckConstraint("ck_communications_status", "status IN ('Ringing','Answered','Missed','Rejected','Blocked','Abandoned','Overflowed','NoAnswer','Failed','Logged')");
                        });
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeliveryNotes")
                        .HasColumnType("text")
                        .HasColumnName("delivery_notes");

                    b.Property<DateTimeOffset?>("FlagChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("flag_changed_at");

                    b.Property<Guid?>("FlagChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("flag_changed_by");

                    b.Property<string>("FlagReason")
                        .HasColumnType("text")
                        .HasColumnName("flag_reason");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_blocked");

                    b.Property<bool>("IsVip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_vip");

                    b.Property<Guid?>("MergedIntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalised")
                        .HasColumnType("text")
                        .HasColumnName("name_normalised");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_contacts_created_by");

                    b.HasIndex("FlagChangedBy")
                        .HasDatabaseName("ix_contacts_flag_changed_by");

                    b.HasIndex("MergedIntoId")
                        .HasDatabaseName("ix_contacts_merged_into_id");

                    b.HasIndex("NameNormalised")
                        .HasDatabaseName("ix_contacts_name_normalised");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_contacts_updated_by");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.ContactPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("Last9")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("last9")
                        .HasComputedColumnSql("right(normalised, 9)", true);

                    b.Property<string>("Normalised")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalised");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw");

                    b.HasKey("Id")
                        .HasName("pk_contact_phones");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_contact_phones_contact_id");

                    b.HasIndex("Last9")
                        .HasDatabaseName("ix_contact_phones_last9");

                    b.HasIndex("Normalised")
                        .IsUnique()
                        .HasDatabaseName("ux_contact_phones_normalised");

                    b.ToTable("contact_phones", (string)null);
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.DeliveryArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalised")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_normalised");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_delivery_areas");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_delivery_area_branch");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_delivery_areas_created_by");

                    b.HasIndex("NameNormalised")
                        .IsUnique()
                        .HasDatabaseName("ux_delivery_area_name");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_delivery_areas_updated_by");

                    b.ToTable("delivery_areas", null, t =>
                        {
                            t.HasCheckConstraint("ck_delivery_areas_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.FollowUpTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by");

                    b.Property<Guid?>("ClosedByCommunicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_communication_id");

                    b.Property<Guid?>("CommunicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("communication_id");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedFrom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_from");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Open")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_follow_up_tasks");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("ix_follow_up_tasks_assigned_to");

                    b.HasIndex("ClosedBy")
                        .HasDatabaseName("ix_follow_up_tasks_closed_by");

                    b.HasIndex("ClosedByCommunicationId")
                        .HasDatabaseName("ix_follow_up_tasks_closed_by_communication_id");

                    b.HasIndex("CommunicationId")
                        .HasDatabaseName("ix_follow_up_tasks_communication_id");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_tasks_contact");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_follow_up_tasks_created_by");

                    b.HasIndex("Status", "DueAt")
                        .HasDatabaseName("ix_tasks_open")
                        .HasFilter("status = 'Open'");

                    b.ToTable("follow_up_tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_follow_up_tasks_created_from", "created_from IN ('Complaint','Abandoned','Missed','Manual')");

                            t.HasCheckConstraint("ck_follow_up_tasks_status", "status IN ('Open','Done','Cancelled')");
                        });
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.FormDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<JsonDocument>("Definition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_current");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_form_definitions");

                    b.HasAlternateKey("Version")
                        .HasName("ak_form_definitions_version");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_form_definitions_created_by");

                    b.HasIndex("IsCurrent")
                        .IsUnique()
                        .HasDatabaseName("ux_form_current")
                        .HasFilter("is_current");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasDatabaseName("ix_form_definitions_version");

                    b.ToTable("form_definitions", (string)null);
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.MenuCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalised")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_normalised");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_menu_categories");

                    b.HasIndex("NameNormalised")
                        .IsUnique()
                        .HasDatabaseName("ux_menu_category_name");

                    b.ToTable("menu_categories", (string)null);
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("image_file_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSurcharge")
                        .HasColumnType("boolean")
                        .HasColumnName("is_surcharge");

                    b.Property<decimal?>("MealPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("meal_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalised")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_normalised");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_menu_items");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_menu_items_created_by");

                    b.HasIndex("NameNormalised")
                        .HasDatabaseName("ix_menu_item_name");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_menu_items_updated_by");

                    b.HasIndex("CategoryId", "NameNormalised")
                        .IsUnique()
                        .HasDatabaseName("ux_menu_item_name_in_category");

                    b.HasIndex("CategoryId", "SortOrder")
                        .HasDatabaseName("ix_menu_item_order");

                    b.ToTable("menu_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_menu_items_meal_price", "meal_price IS NULL OR meal_price >= 0");

                            t.HasCheckConstraint("ck_menu_items_price", "price IS NULL OR price >= 0");
                        });
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.OutboxSync", b =>
                {
                    b.Property<Guid>("ClientOpId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_op_id");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ClientOpId")
                        .HasName("pk_outbox_sync");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_outbox_sync_user_id");

                    b.ToTable("outbox_sync", (string)null);
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.PbxEventRaw", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("EventName")
                        .HasColumnType("text")
                        .HasColumnName("event_name");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_pbx_events_raw");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_pbx_events_received");

                    b.ToTable("pbx_events_raw", null, t =>
                        {
                            t.HasCheckConstraint("ck_pbx_events_raw_source", "source IN ('AMI','CDR','SIP')");
                        });
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.Recording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CommunicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("communication_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("integer")
                        .HasColumnName("duration_sec");

                    b.Property<string>("Format")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("wav")
                        .HasColumnName("format");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_recordings");

                    b.HasIndex("CommunicationId")
                        .IsUnique()
                        .HasDatabaseName("ix_recordings_communication_id");

                    b.ToTable("recordings", (string)null);
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_settings");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_settings_updated_by");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Extension")
                        .HasColumnType("text")
                        .HasColumnName("extension");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("SipSecret")
                        .HasColumnType("text")
                        .HasColumnName("sip_secret");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ix_users_login");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('Agent','Supervisor')");
                        });
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.AgentSession", b =>
                {
                    b.HasOne("CallCenter.Server.Data.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agent_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.AuditLogEntry", b =>
                {
                    b.HasOne("CallCenter.Server.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_log_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.Classification", b =>
                {
                    b.HasOne("CallCenter.Server.Data.Entities.User", "ClassifiedByUser")
                        .WithMany()
                        .HasForeignKey("ClassifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classifications_users_classified_by");

                    b.HasOne("CallCenter.Server.Data.Entities.Communication", "Communication")
                        .WithOne("Classification")
                        .HasForeignKey("CallCenter.Server.Data.Entities.Classification", "CommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_classifications_communications_communication_id");

                    b.HasOne("CallCenter.Server.Data.Entities.FormDefinition", "Form")
                        .WithMany()
                        .HasForeignKey("FormVersion")
                        .HasPrincipalKey("Version")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classifications_form_definitions_form_version");

                    b.HasOne("CallCenter.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_classifications_users_resolved_by");

                    b.HasOne("CallCenter.Server.Data.Entities.ClassificationType", "Type")
                        .WithMany("Classifications")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classifications_classification_types_type_id");

                    b.HasOne("CallCenter.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_classifications_users_updated_by");

                    b.Navigation("ClassifiedByUser");

                    b.Navigation("Communication");

                    b.Navigation("Form");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.ClassificationHistory", b =>
                {
                    b.HasOne("CallCenter.Server.Data.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classification_history_users_changed_by");

                    b.HasOne("CallCenter.Server.Data.Entities.Communication", null)
                        .WithMany()
                        .HasForeignKey("CommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_classification_history_communications_communication_id");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.Communication", b =>
                {
                    b.HasOne("CallCenter.Server.Data.Entities.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_communications_users_agent_id");

                    b.HasOne("CallCenter.Server.Data.Entities.Branch", "Branch")
                        .WithMany("Communications")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_communications_branches_branch_id");

                    b.HasOne("CallCenter.Server.Data.Entities.Channel", "Channel")
                        .WithMany("Communications")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_communications_channels_channel_id");

                    b.HasOne("CallCenter.Server.Data.Entities.Contact", "Contact")
                        .WithMany("Communications")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_communications_contacts_contact_id");

                    b.Navigation("Agent");

                    b.Navigation("Branch");

                    b.Navigation("Channel");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.Contact", b =>
                {
                    b.HasOne("CallCenter.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contacts_users_created_by");

                    b.HasOne("CallCenter.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("FlagChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contacts_users_flag_changed_by");

                    b.HasOne("CallCenter.Server.Data.Entities.Contact", "MergedInto")
                        .WithMany()
                        .HasForeignKey("MergedIntoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contacts_contacts_merged_into_id");

                    b.HasOne("CallCenter.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contacts_users_updated_by");

                    b.Navigation("MergedInto");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.ContactPhone", b =>
                {
                    b.HasOne("CallCenter.Server.Data.Entities.Contact", "Contact")
                        .WithMany("Phones")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_phones_contacts_contact_id");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.DeliveryArea", b =>
                {
                    b.HasOne("CallCenter.Server.Data.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_areas_branches_branch_id");

                    b.HasOne("CallCenter.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_delivery_areas_users_created_by");

                    b.HasOne("CallCenter.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_delivery_areas_users_updated_by");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.FollowUpTask", b =>
                {
                    b.HasOne("CallCenter.Server.Data.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_follow_up_tasks_users_assigned_to");

                    b.HasOne("CallCenter.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ClosedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_follow_up_tasks_users_closed_by");

                    b.HasOne("CallCenter.Server.Data.Entities.Communication", "ClosedByCommunication")
                        .WithMany()
                        .HasForeignKey("ClosedByCommunicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_follow_up_tasks_communications_closed_by_communication_id");

                    b.HasOne("CallCenter.Server.Data.Entities.Communication", "Communication")
                        .WithMany()
                        .HasForeignKey("CommunicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_follow_up_tasks_communications_communication_id");

                    b.HasOne("CallCenter.Server.Data.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_follow_up_tasks_contacts_contact_id");

                    b.HasOne("CallCenter.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_follow_up_tasks_users_created_by");

                    b.Navigation("AssignedToUser");

                    b.Navigation("ClosedByCommunication");

                    b.Navigation("Communication");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.FormDefinition", b =>
                {
                    b.HasOne("CallCenter.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_definitions_users_created_by");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.MenuItem", b =>
                {
                    b.HasOne("CallCenter.Server.Data.Entities.MenuCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_menu_items_menu_categories_category_id");

                    b.HasOne("CallCenter.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_menu_items_users_created_by");

                    b.HasOne("CallCenter.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_menu_items_users_updated_by");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.OutboxSync", b =>
                {
                    b.HasOne("CallCenter.Server.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_outbox_sync_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.Recording", b =>
                {
                    b.HasOne("CallCenter.Server.Data.Entities.Communication", "Communication")
                        .WithOne("Recording")
                        .HasForeignKey("CallCenter.Server.Data.Entities.Recording", "CommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recordings_communications_communication_id");

                    b.Navigation("Communication");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.Setting", b =>
                {
                    b.HasOne("CallCenter.Server.Data.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_settings_users_updated_by");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.Branch", b =>
                {
                    b.Navigation("Communications");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.Channel", b =>
                {
                    b.Navigation("Communications");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.ClassificationType", b =>
                {
                    b.Navigation("Classifications");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.Communication", b =>
                {
                    b.Navigation("Classification");

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.Contact", b =>
                {
                    b.Navigation("Communications");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.MenuCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CallCenter.Server.Data.Entities.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
