using System.Text.Json;
using CallCenter.Server.Data;
using CallCenter.Server.Data.Entities;
using CallCenter.Shared.Contracts.Contacts;
using CallCenter.Shared.Phone;
using Microsoft.EntityFrameworkCore;

namespace CallCenter.Server.Features.Contacts;

/// <summary>
/// The shared contact list (A-60 to A-63). Every agent sees every contact.
/// </summary>
/// <remarks>
/// Numbers are stored twice over: <c>normalised</c> as this service writes it,
/// and <c>last9</c> generated by PostgreSQL. Matching tries the normalised form
/// first and falls back to the last nine digits, which is what makes 05…,
/// +9705… and 9705… the same number (A-13). The normalising rules live in
/// <see cref="PhoneNormalizer"/> and are never re-implemented here.
/// </remarks>
public class ContactsService(CallCenterDbContext db, ILogger<ContactsService> logger)
{
    /// <summary>How many results a search returns before the caller must narrow it.</summary>
    public const int SearchLimit = 50;

    public enum Failure
    {
        NotFound,

        /// <summary>Every number was blank once normalised, so nothing could be stored.</summary>
        NoUsableNumber,

        /// <summary>A number already belongs to another contact (A-63).</summary>
        DuplicateNumber,
    }

    /// <summary>
    /// Searches by name, address or phone number (A-61).
    /// </summary>
    /// <remarks>
    /// A query of digits is treated as a number and matched the way caller lookup
    /// does; anything else is matched against name and address. That guess is
    /// what lets one box serve both, which is what A-61 asks for.
    /// </remarks>
    public async Task<IReadOnlyList<ContactSummaryDto>> SearchAsync(
        string? query, CancellationToken ct = default)
    {
        var contacts = Active();

        if (!string.IsNullOrWhiteSpace(query))
        {
            var digits = PhoneNormalizer.DigitsOnly(query);

            // Three or more digits and nothing else: the agent is typing a number.
            if (digits.Length >= 3 && digits.Length == query.Trim().Length)
            {
                var normalised = PhoneNormalizer.Normalize(query);
                var last9 = PhoneNormalizer.Last9(query);

                contacts = contacts.Where(c => c.Phones.Any(p =>
                    p.Normalised == normalised
                    || p.Last9 == last9
                    || p.Normalised.Contains(digits)));
            }
            else
            {
                var like = $"%{query.Trim()}%";

                // ILIKE rather than the full-text index: the index is built over
                // to_tsvector with the default configuration, which does not stem
                // Arabic, so it would miss the names most contacts actually have.
                contacts = contacts.Where(c =>
                    (c.Name != null && EF.Functions.ILike(c.Name, like))
                    || (c.Address != null && EF.Functions.ILike(c.Address, like)));
            }
        }

        return await contacts
            .OrderByDescending(c => c.IsVip)
            .ThenBy(c => c.Name)
            .Take(SearchLimit)
            .Select(c => new ContactSummaryDto(
                c.Id,
                c.Name,
                c.Address,
                c.IsVip,
                c.IsBlocked,
                c.Phones.OrderByDescending(p => p.IsPrimary).Select(p => p.Raw).ToList()))
            .ToListAsync(ct);
    }

    /// <summary>One contact in full (A-62).</summary>
    public async Task<ContactDto?> GetAsync(Guid id, CancellationToken ct = default)
    {
        var contact = await Active()
            .Include(c => c.Phones)
            .FirstOrDefaultAsync(c => c.Id == id, ct);

        return contact is null ? null : ToDto(contact, await CreatorNameAsync(contact, ct));
    }

    /// <summary>
    /// Finds the contact a number belongs to — the lookup behind the
    /// incoming-call pop-up (A-10, A-13).
    /// </summary>
    /// <remarks>
    /// Exact normalised match first, then the last nine digits. The fallback
    /// matters: a caller may present 0599123456 while the contact was saved as
    /// +970599123456, and those must be one person.
    /// </remarks>
    public async Task<ContactDto?> FindByPhoneAsync(string number, CancellationToken ct = default)
    {
        var normalised = PhoneNormalizer.Normalize(number);
        if (string.IsNullOrEmpty(normalised))
        {
            return null;
        }

        var contact = await Active()
            .Include(c => c.Phones)
            .FirstOrDefaultAsync(c => c.Phones.Any(p => p.Normalised == normalised), ct);

        if (contact is null)
        {
            var last9 = PhoneNormalizer.Last9(number);

            // Short numbers have no meaningful tail, so do not guess with them:
            // every internal extension would collide.
            if (last9.Length == 9)
            {
                contact = await Active()
                    .Include(c => c.Phones)
                    .FirstOrDefaultAsync(c => c.Phones.Any(p => p.Last9 == last9), ct);
            }
        }

        return contact is null ? null : ToDto(contact, await CreatorNameAsync(contact, ct));
    }

    /// <summary>Creates a contact (A-63).</summary>
    public async Task<(ContactDto? Contact, Failure? Failure, DuplicateNumberDto? Duplicate)> CreateAsync(
        UpsertContactRequest request, Guid actingUserId, CancellationToken ct = default)
    {
        var numbers = Normalise(request.Phones);
        if (numbers.Count == 0)
        {
            return (null, Failure.NoUsableNumber, null);
        }

        if (await FindDuplicateAsync(numbers.Select(n => n.Normalised), null, ct) is { } duplicate)
        {
            return (null, Failure.DuplicateNumber, duplicate);
        }

        var contact = new Contact
        {
            Name = Trimmed(request.Name),
            Address = Trimmed(request.Address),
            Notes = Trimmed(request.Notes),
            DeliveryNotes = Trimmed(request.DeliveryNotes),
            CreatedBy = actingUserId,
            UpdatedBy = actingUserId,
        };

        for (var i = 0; i < numbers.Count; i++)
        {
            contact.Phones.Add(new ContactPhone
            {
                Raw = numbers[i].Raw,
                Normalised = numbers[i].Normalised,
                IsPrimary = i == 0,
            });
        }

        db.Contacts.Add(contact);
        await db.SaveChangesAsync(ct);
        await AuditAsync(actingUserId, "create", contact, before: null, ct);

        logger.LogInformation("Contact {ContactId} created with {Count} number(s)", contact.Id, numbers.Count);

        return (ToDto(contact, null), null, null);
    }

    /// <summary>
    /// Replaces a contact's details and numbers (A-63). The flags are untouched —
    /// only a supervisor changes those (S-45).
    /// </summary>
    public async Task<(ContactDto? Contact, Failure? Failure, DuplicateNumberDto? Duplicate)> UpdateAsync(
        Guid id, UpsertContactRequest request, Guid actingUserId, CancellationToken ct = default)
    {
        var contact = await Active().Include(c => c.Phones).FirstOrDefaultAsync(c => c.Id == id, ct);
        if (contact is null)
        {
            return (null, Failure.NotFound, null);
        }

        var numbers = Normalise(request.Phones);
        if (numbers.Count == 0)
        {
            return (null, Failure.NoUsableNumber, null);
        }

        if (await FindDuplicateAsync(numbers.Select(n => n.Normalised), id, ct) is { } duplicate)
        {
            return (null, Failure.DuplicateNumber, duplicate);
        }

        var before = Snapshot(contact);

        contact.Name = Trimmed(request.Name);
        contact.Address = Trimmed(request.Address);
        contact.Notes = Trimmed(request.Notes);
        contact.DeliveryNotes = Trimmed(request.DeliveryNotes);
        contact.UpdatedBy = actingUserId;
        contact.UpdatedAt = DateTimeOffset.UtcNow;

        // The list sent is the list afterwards. Rows that survive keep their id,
        // so a number that was only re-ordered does not look newly added in the
        // audit trail.
        var keep = numbers.Select(n => n.Normalised).ToHashSet();

        foreach (var gone in contact.Phones.Where(p => !keep.Contains(p.Normalised)).ToList())
        {
            db.ContactPhones.Remove(gone);
        }

        for (var i = 0; i < numbers.Count; i++)
        {
            var existing = contact.Phones.FirstOrDefault(p => p.Normalised == numbers[i].Normalised);

            if (existing is null)
            {
                contact.Phones.Add(new ContactPhone
                {
                    Raw = numbers[i].Raw,
                    Normalised = numbers[i].Normalised,
                    IsPrimary = i == 0,
                });
            }
            else
            {
                existing.Raw = numbers[i].Raw;
                existing.IsPrimary = i == 0;
            }
        }

        await db.SaveChangesAsync(ct);
        await AuditAsync(actingUserId, "update", contact, before, ct);

        return (ToDto(contact, await CreatorNameAsync(contact, ct)), null, null);
    }

    /// <summary>
    /// Contacts that are neither merged away nor deleted. A merged contact stays
    /// on file so its history survives, but it must not appear in a search.
    /// </summary>
    private IQueryable<Contact> Active() =>
        db.Contacts.Where(c => c.DeletedAt == null && c.MergedIntoId == null);

    /// <summary>
    /// The first number already on another contact, if any (A-63). Checked
    /// before saving so the answer names the other contact, rather than letting
    /// the unique index fail with something unreadable.
    /// </summary>
    private async Task<DuplicateNumberDto?> FindDuplicateAsync(
        IEnumerable<string> normalised, Guid? excludingContactId, CancellationToken ct)
    {
        var numbers = normalised.ToList();

        var clash = await db.ContactPhones
            .Where(p => numbers.Contains(p.Normalised))
            .Where(p => excludingContactId == null || p.ContactId != excludingContactId)
            .Select(p => new { p.Normalised, p.ContactId, p.Contact.Name })
            .FirstOrDefaultAsync(ct);

        return clash is null ? null : new DuplicateNumberDto(clash.Normalised, clash.ContactId, clash.Name);
    }

    /// <summary>
    /// Normalises the submitted numbers, dropping blanks and keeping the first
    /// spelling of any number given twice. Order is preserved: the first is the
    /// primary.
    /// </summary>
    private static List<(string Raw, string Normalised)> Normalise(IEnumerable<string> phones)
    {
        var result = new List<(string Raw, string Normalised)>();
        var seen = new HashSet<string>();

        foreach (var raw in phones)
        {
            var normalised = PhoneNormalizer.Normalize(raw);
            if (string.IsNullOrEmpty(normalised) || !seen.Add(normalised))
            {
                continue;
            }

            result.Add((raw.Trim(), normalised));
        }

        return result;
    }

    private static string? Trimmed(string? value) =>
        string.IsNullOrWhiteSpace(value) ? null : value.Trim();

    private async Task<string?> CreatorNameAsync(Contact contact, CancellationToken ct) =>
        contact.CreatedBy is null
            ? null
            : await db.Users.Where(u => u.Id == contact.CreatedBy)
                .Select(u => u.DisplayName)
                .FirstOrDefaultAsync(ct);

    private static ContactDto ToDto(Contact contact, string? createdByDisplayName) => new(
        contact.Id,
        contact.Name,
        contact.Address,
        contact.Notes,
        contact.DeliveryNotes,
        contact.IsVip,
        contact.IsBlocked,
        contact.FlagReason,
        contact.Phones
            .OrderByDescending(p => p.IsPrimary)
            .Select(p => new ContactPhoneDto(p.Id, p.Raw, p.Normalised, p.IsPrimary))
            .ToList(),
        createdByDisplayName,
        contact.CreatedAt,
        contact.UpdatedAt);

    private static JsonDocument Snapshot(Contact contact) => JsonSerializer.SerializeToDocument(new
    {
        contact.Name,
        contact.Address,
        contact.Notes,
        contact.DeliveryNotes,
        Phones = contact.Phones.Select(p => p.Normalised).OrderBy(n => n).ToList(),
    });

    private async Task AuditAsync(
        Guid actingUserId, string action, Contact contact, JsonDocument? before, CancellationToken ct)
    {
        db.AuditLog.Add(new AuditLogEntry
        {
            UserId = actingUserId,
            Entity = "contact",
            EntityId = contact.Id.ToString(),
            Action = action,
            Before = before,
            After = Snapshot(contact),
        });

        await db.SaveChangesAsync(ct);
    }
}
