using System.Text.Json;
using CallCenter.Server.Data;
using CallCenter.Server.Data.Entities;
using CallCenter.Shared.Contracts.Contacts;
using CallCenter.Shared.Phone;
using CallCenter.Shared.Text;
using Microsoft.EntityFrameworkCore;

namespace CallCenter.Server.Features.Contacts;

/// <summary>
/// The shared contact list (A-60 to A-63). Every agent sees every contact.
/// </summary>
/// <remarks>
/// Numbers are stored twice over: <c>normalised</c> as this service writes it,
/// and <c>last9</c> generated by PostgreSQL. Matching tries the normalised form
/// first and falls back to the last nine digits, which is what makes 05…,
/// +9705… and 9705… the same number (A-13). The normalising rules live in
/// <see cref="PhoneNormalizer"/> and are never re-implemented here.
/// </remarks>
public class ContactsService(CallCenterDbContext db, ILogger<ContactsService> logger)
{
    /// <summary>How many results a search returns before the caller must narrow it.</summary>
    public const int SearchLimit = 50;

    /// <summary>
    /// How many same-name contacts are offered as a warning. Short on purpose:
    /// it is a prompt to look, not a list to work through.
    /// </summary>
    public const int NameWarningLimit = 5;

    public enum Failure
    {
        NotFound,

        /// <summary>Every number was blank once normalised, so nothing could be stored.</summary>
        NoUsableNumber,

        /// <summary>A number already belongs to another contact (A-63).</summary>
        DuplicateNumber,
    }

    /// <summary>
    /// Searches by name, address or phone number (A-61), optionally narrowed to
    /// the flagged contacts (S-45).
    /// </summary>
    /// <remarks>
    /// A query of digits is treated as a number and matched the way caller lookup
    /// does; anything else is matched against name and address. That guess is
    /// what lets one box serve both, which is what A-61 asks for.
    ///
    /// The flag filter is here rather than on an endpoint of its own so that the
    /// two compose: "blocked contacts in Ramallah" is one query, and the list of
    /// every blocked number S-45 asks for is this with an empty search box.
    /// </remarks>
    /// <param name="flag">
    /// <c>vip</c>, <c>blocked</c>, or null for everything. Anything else is
    /// ignored rather than refused — a filter is a view, and a stale bookmark
    /// should show the contact list, not an error.
    /// </param>
    public async Task<IReadOnlyList<ContactSummaryDto>> SearchAsync(
        string? query, string? flag = null, CancellationToken ct = default)
    {
        var contacts = Active();

        contacts = flag?.ToLowerInvariant() switch
        {
            "vip" => contacts.Where(c => c.IsVip),
            "blocked" => contacts.Where(c => c.IsBlocked),
            _ => contacts,
        };

        if (!string.IsNullOrWhiteSpace(query))
        {
            var digits = PhoneNormalizer.DigitsOnly(query);

            // Three or more digits and nothing else: the agent is typing a number.
            if (digits.Length >= 3 && digits.Length == query.Trim().Length)
            {
                var normalised = PhoneNormalizer.Normalize(query);
                var last9 = PhoneNormalizer.Last9(query);

                contacts = contacts.Where(c => c.Phones.Any(p =>
                    p.Normalised == normalised
                    || p.Last9 == last9
                    || p.Normalised.Contains(digits)));
            }
            else
            {
                var like = $"%{query.Trim()}%";

                // ILIKE rather than the full-text index: the index is built over
                // to_tsvector with the default configuration, which does not stem
                // Arabic, so it would miss the names most contacts actually have.
                // The normalised name, not the stored one: searching for
                // "احمد" must find a contact saved as "أحمد" (A-80).
                var normalisedLike = $"%{NameNormalizer.Normalize(query)}%";

                contacts = contacts.Where(c =>
                    (c.NameNormalised != null && EF.Functions.ILike(c.NameNormalised, normalisedLike))
                    || (c.Address != null && EF.Functions.ILike(c.Address, like)));
            }
        }

        return await contacts
            .OrderByDescending(c => c.IsVip)
            .ThenBy(c => c.Name)
            .Take(SearchLimit)
            .Select(c => new ContactSummaryDto(
                c.Id,
                c.Name,
                c.Address,
                c.IsVip,
                c.IsBlocked,
                c.FlagReason,
                c.Phones.OrderByDescending(p => p.IsPrimary).Select(p => p.Raw).ToList()))
            .ToListAsync(ct);
    }

    /// <summary>
    /// Contacts that already carry this name (A-63). A warning for the agent,
    /// never a refusal — see the remarks.
    /// </summary>
    /// <remarks>
    /// Names are never matched automatically. "أحمد" and "محمد" are common, and
    /// silently joining two customers would mix their order histories with no
    /// way to unpick them afterwards. So this only tells the agent what already
    /// exists; they decide whether it is the same person.
    ///
    /// The match is <b>exact</b>, on the normalised form. Substring matching was
    /// tried and rejected: "Ahmad" is a common name, so it would warn about a
    /// dozen unrelated people every time and be ignored within a week. Exact
    /// matching only works because of the normalising — PostgreSQL considers
    /// <c>'أحمد' = 'احمد'</c> false, so comparing stored names directly would
    /// almost never fire.
    /// </remarks>
    public async Task<IReadOnlyList<ContactSummaryDto>> FindByNameAsync(
        string? name, Guid? excludingContactId = null, CancellationToken ct = default)
    {
        var normalised = NameNormalizer.Normalize(name);

        if (normalised.Length == 0)
        {
            return [];
        }

        return await Active()
            .Where(c => c.NameNormalised == normalised)
            .Where(c => excludingContactId == null || c.Id != excludingContactId)
            .OrderBy(c => c.Name)
            .Take(NameWarningLimit)
            .Select(c => new ContactSummaryDto(
                c.Id,
                c.Name,
                c.Address,
                c.IsVip,
                c.IsBlocked,
                c.FlagReason,
                c.Phones.OrderByDescending(p => p.IsPrimary).Select(p => p.Raw).ToList()))
            .ToListAsync(ct);
    }

    /// <summary>
    /// Adds one number to a contact that already exists (A-63) — the other half
    /// of the name warning, for when the agent says "yes, same person".
    /// </summary>
    /// <remarks>
    /// Deliberately not a full update: the agent answering that question has
    /// typed a number and nothing else, and sending the whole contact back would
    /// risk blanking an address or notes they never saw.
    /// </remarks>
    public async Task<(ContactDto? Contact, Failure? Failure, DuplicateNumberDto? Duplicate)> AddPhoneAsync(
        Guid id, string number, Guid actingUserId, CancellationToken ct = default)
    {
        var contact = await Active().Include(c => c.Phones).FirstOrDefaultAsync(c => c.Id == id, ct);
        if (contact is null)
        {
            return (null, Failure.NotFound, null);
        }

        var normalised = PhoneNormalizer.Normalize(number);
        if (string.IsNullOrEmpty(normalised))
        {
            return (null, Failure.NoUsableNumber, null);
        }

        // Already on this contact: nothing to do, and not an error - the agent
        // asked for an outcome that is already true.
        if (contact.Phones.Any(p => p.Normalised == normalised))
        {
            return (ToDto(contact, await CreatorNameAsync(contact, ct)), null, null);
        }

        if (await FindDuplicateAsync([normalised], id, ct) is { } duplicate)
        {
            return (null, Failure.DuplicateNumber, duplicate);
        }

        var before = Snapshot(contact);

        contact.Phones.Add(new ContactPhone
        {
            Raw = number.Trim(),
            Normalised = normalised,
            IsPrimary = contact.Phones.Count == 0,
        });

        contact.UpdatedBy = actingUserId;
        contact.UpdatedAt = DateTimeOffset.UtcNow;

        await db.SaveChangesAsync(ct);
        await AuditAsync(actingUserId, "add-phone", contact, before, ct);

        logger.LogInformation("Number added to contact {ContactId}", contact.Id);

        return (ToDto(contact, await CreatorNameAsync(contact, ct)), null, null);
    }

    /// <summary>One contact in full (A-62).</summary>
    public async Task<ContactDto?> GetAsync(Guid id, CancellationToken ct = default)
    {
        var contact = await Active()
            .Include(c => c.Phones)
            .FirstOrDefaultAsync(c => c.Id == id, ct);

        return contact is null ? null : ToDto(contact, await CreatorNameAsync(contact, ct));
    }

    /// <summary>
    /// Finds the contact a number belongs to — the lookup behind the
    /// incoming-call pop-up (A-10, A-13).
    /// </summary>
    /// <remarks>
    /// Exact normalised match first, then the last nine digits. The fallback
    /// matters: a caller may present 0599123456 while the contact was saved as
    /// +970599123456, and those must be one person.
    /// </remarks>
    public async Task<ContactDto?> FindByPhoneAsync(string number, CancellationToken ct = default)
    {
        var normalised = PhoneNormalizer.Normalize(number);
        if (string.IsNullOrEmpty(normalised))
        {
            return null;
        }

        var contact = await Active()
            .Include(c => c.Phones)
            .FirstOrDefaultAsync(c => c.Phones.Any(p => p.Normalised == normalised), ct);

        if (contact is null)
        {
            var last9 = PhoneNormalizer.Last9(number);

            // Short numbers have no meaningful tail, so do not guess with them:
            // every internal extension would collide.
            if (last9.Length == 9)
            {
                contact = await Active()
                    .Include(c => c.Phones)
                    .FirstOrDefaultAsync(c => c.Phones.Any(p => p.Last9 == last9), ct);
            }
        }

        return contact is null ? null : ToDto(contact, await CreatorNameAsync(contact, ct));
    }

    /// <summary>Creates a contact (A-63).</summary>
    public async Task<(ContactDto? Contact, Failure? Failure, DuplicateNumberDto? Duplicate)> CreateAsync(
        UpsertContactRequest request, Guid actingUserId, CancellationToken ct = default)
    {
        var numbers = Normalise(request.Phones);
        if (numbers.Count == 0)
        {
            return (null, Failure.NoUsableNumber, null);
        }

        if (await FindDuplicateAsync(numbers.Select(n => n.Normalised), null, ct) is { } duplicate)
        {
            return (null, Failure.DuplicateNumber, duplicate);
        }

        var contact = new Contact
        {
            Name = Trimmed(request.Name),
            NameNormalised = NormalisedName(request.Name),
            Address = Trimmed(request.Address),
            Notes = Trimmed(request.Notes),
            DeliveryNotes = Trimmed(request.DeliveryNotes),
            CreatedBy = actingUserId,
            UpdatedBy = actingUserId,
        };

        for (var i = 0; i < numbers.Count; i++)
        {
            contact.Phones.Add(new ContactPhone
            {
                Raw = numbers[i].Raw,
                Normalised = numbers[i].Normalised,
                IsPrimary = i == 0,
            });
        }

        db.Contacts.Add(contact);
        await db.SaveChangesAsync(ct);
        await AuditAsync(actingUserId, "create", contact, before: null, ct);

        logger.LogInformation("Contact {ContactId} created with {Count} number(s)", contact.Id, numbers.Count);

        return (ToDto(contact, null), null, null);
    }

    /// <summary>
    /// Replaces a contact's details and numbers (A-63). The flags are untouched —
    /// only a supervisor changes those (S-45).
    /// </summary>
    public async Task<(ContactDto? Contact, Failure? Failure, DuplicateNumberDto? Duplicate)> UpdateAsync(
        Guid id, UpsertContactRequest request, Guid actingUserId, CancellationToken ct = default)
    {
        var contact = await Active().Include(c => c.Phones).FirstOrDefaultAsync(c => c.Id == id, ct);
        if (contact is null)
        {
            return (null, Failure.NotFound, null);
        }

        var numbers = Normalise(request.Phones);
        if (numbers.Count == 0)
        {
            return (null, Failure.NoUsableNumber, null);
        }

        if (await FindDuplicateAsync(numbers.Select(n => n.Normalised), id, ct) is { } duplicate)
        {
            return (null, Failure.DuplicateNumber, duplicate);
        }

        var before = Snapshot(contact);

        contact.Name = Trimmed(request.Name);
        contact.NameNormalised = NormalisedName(request.Name);
        contact.Address = Trimmed(request.Address);
        contact.Notes = Trimmed(request.Notes);
        contact.DeliveryNotes = Trimmed(request.DeliveryNotes);
        contact.UpdatedBy = actingUserId;
        contact.UpdatedAt = DateTimeOffset.UtcNow;

        // The list sent is the list afterwards. Rows that survive keep their id,
        // so a number that was only re-ordered does not look newly added in the
        // audit trail.
        var keep = numbers.Select(n => n.Normalised).ToHashSet();

        foreach (var gone in contact.Phones.Where(p => !keep.Contains(p.Normalised)).ToList())
        {
            db.ContactPhones.Remove(gone);
        }

        for (var i = 0; i < numbers.Count; i++)
        {
            var existing = contact.Phones.FirstOrDefault(p => p.Normalised == numbers[i].Normalised);

            if (existing is null)
            {
                contact.Phones.Add(new ContactPhone
                {
                    Raw = numbers[i].Raw,
                    Normalised = numbers[i].Normalised,
                    IsPrimary = i == 0,
                });
            }
            else
            {
                existing.Raw = numbers[i].Raw;
                existing.IsPrimary = i == 0;
            }
        }

        await db.SaveChangesAsync(ct);
        await AuditAsync(actingUserId, "update", contact, before, ct);

        return (ToDto(contact, await CreatorNameAsync(contact, ct)), null, null);
    }

    /// <summary>
    /// Contacts that are neither merged away nor deleted. A merged contact stays
    /// on file so its history survives, but it must not appear in a search.
    /// </summary>
    private IQueryable<Contact> Active() =>
        db.Contacts.Where(c => c.DeletedAt == null && c.MergedIntoId == null);

    /// <summary>
    /// The first number already on another contact, if any (A-63). Checked
    /// before saving so the answer names the other contact, rather than letting
    /// the unique index fail with something unreadable.
    /// </summary>
    private async Task<DuplicateNumberDto?> FindDuplicateAsync(
        IEnumerable<string> normalised, Guid? excludingContactId, CancellationToken ct)
    {
        var numbers = normalised.ToList();

        var clash = await db.ContactPhones
            .Where(p => numbers.Contains(p.Normalised))
            .Where(p => excludingContactId == null || p.ContactId != excludingContactId)
            .Select(p => new { p.Normalised, p.ContactId, p.Contact.Name })
            .FirstOrDefaultAsync(ct);

        return clash is null ? null : new DuplicateNumberDto(clash.Normalised, clash.ContactId, clash.Name);
    }

    /// <summary>
    /// Normalises the submitted numbers, dropping blanks and keeping the first
    /// spelling of any number given twice. Order is preserved: the first is the
    /// primary.
    /// </summary>
    private static List<(string Raw, string Normalised)> Normalise(IEnumerable<string> phones)
    {
        var result = new List<(string Raw, string Normalised)>();
        var seen = new HashSet<string>();

        foreach (var raw in phones)
        {
            var normalised = PhoneNormalizer.Normalize(raw);
            if (string.IsNullOrEmpty(normalised) || !seen.Add(normalised))
            {
                continue;
            }

            result.Add((raw.Trim(), normalised));
        }

        return result;
    }

    private static string? Trimmed(string? value) =>
        string.IsNullOrWhiteSpace(value) ? null : value.Trim();

    /// <summary>
    /// The comparison form of a name, or null when there is no name. Null rather
    /// than an empty string on purpose: a bare number saved for flagging (S-45)
    /// must not match every other nameless contact.
    /// </summary>
    private static string? NormalisedName(string? name)
    {
        var normalised = NameNormalizer.Normalize(name);
        return normalised.Length == 0 ? null : normalised;
    }

    private async Task<string?> CreatorNameAsync(Contact contact, CancellationToken ct) =>
        contact.CreatedBy is null
            ? null
            : await db.Users.Where(u => u.Id == contact.CreatedBy)
                .Select(u => u.DisplayName)
                .FirstOrDefaultAsync(ct);

    private static ContactDto ToDto(Contact contact, string? createdByDisplayName) => new(
        contact.Id,
        contact.Name,
        contact.Address,
        contact.Notes,
        contact.DeliveryNotes,
        contact.IsVip,
        contact.IsBlocked,
        contact.FlagReason,
        contact.Phones
            .OrderByDescending(p => p.IsPrimary)
            .Select(p => new ContactPhoneDto(p.Id, p.Raw, p.Normalised, p.IsPrimary))
            .ToList(),
        createdByDisplayName,
        contact.CreatedAt,
        contact.UpdatedAt);

    /// <summary>
    /// The rest of what the incoming-call pop-up shows about a customer: their
    /// totals and their last few calls, with what each one was about (A-10).
    /// </summary>
    /// <remarks>
    /// <b>Counts are of classified calls only.</b> A call nobody classified is
    /// not an order that did not happen; it is a call nobody wrote down.
    /// Counting it as anything would invent history, so it is counted as
    /// nothing and the agent sees totals that only ever understate.
    ///
    /// Three counts in one grouped query rather than three round trips, and the
    /// recent list in a second: both ride the <c>ix_comm_contact</c> index, and
    /// one customer's calls are few enough that no time window is needed.
    ///
    /// Direction is not filtered. A customer this branch rang and a customer
    /// who rang in are the same relationship, and an agent about to speak wants
    /// the last five times anybody spoke to them (A-21).
    /// </remarks>
    public async Task<CallerCardDto> CardAsync(
        Guid contactId, int recent = 5, CancellationToken ct = default)
    {
        var counts = await db.Classifications
            .AsNoTracking()
            .Where(c => c.Communication.ContactId == contactId)
            .GroupBy(c => c.Type.Name)
            .Select(g => new { Name = g.Key, Count = g.Count() })
            .ToListAsync(ct);

        int Count(string name) =>
            counts.FirstOrDefault(c => c.Name == name)?.Count ?? 0;

        var history = await db.Communications
            .AsNoTracking()
            .Where(c => c.ContactId == contactId)
            .OrderByDescending(c => c.StartedAt)
            .Take(recent)
            .Select(c => new CallerHistoryDto(
                c.StartedAt,
                c.Direction,
                c.Status,
                c.DurationSec,
                // Left-joined: a call nobody classified still belongs in the
                // list. "Three calls, none written up" is itself worth knowing.
                c.Classification == null ? null : c.Classification.Type.Name,
                c.Classification == null ? null : c.Classification.Type.LabelAr,
                c.Classification == null ? null : c.Classification.Type.LabelEn,
                c.Classification == null ? null : c.Classification.Notes))
            .ToListAsync(ct);

        return new CallerCardDto(
            Orders: Count("Order"),
            Complaints: Count("Complaint"),
            Cancellations: Count("Cancellation"),
            Recent: history);
    }

    private static JsonDocument Snapshot(Contact contact) => JsonSerializer.SerializeToDocument(new
    {
        contact.Name,
        contact.Address,
        contact.Notes,
        contact.DeliveryNotes,
        Phones = contact.Phones.Select(p => p.Normalised).OrderBy(n => n).ToList(),
    });

    private async Task AuditAsync(
        Guid actingUserId, string action, Contact contact, JsonDocument? before, CancellationToken ct)
    {
        db.AuditLog.Add(new AuditLogEntry
        {
            UserId = actingUserId,
            Entity = "contact",
            EntityId = contact.Id.ToString(),
            Action = action,
            Before = before,
            After = Snapshot(contact),
        });

        await db.SaveChangesAsync(ct);
    }
}
